[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yggdrasil"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "requests",
  "polars",
  "pandas>=2",
  "numpy>=1.26,<=2.2.6",
  "pyarrow>=16",
  "dill"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-asyncio",
  "black",
  "ruff",
  "mypy",

  "databricks-sdk",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
